# Generated by Django 2.2.5 on 2021-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.TextField(verbose_name='公司网址'),
        ),
    ]
