# Generated by Django 2.2.5 on 2021-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='客户名称')),
                ('briefinfo', models.TextField(verbose_name='客户简介')),
                ('area', models.CharField(max_length=30, verbose_name='所属地区')),
                ('type', models.CharField(max_length=20, verbose_name='客户类型')),
                ('nature', models.CharField(max_length=20, verbose_name='企业性质')),
                ('describe', models.TextField(verbose_name='企业描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('supplier', models.CharField(max_length=20, verbose_name='供应商')),
                ('num', models.CharField(max_length=10, verbose_name='产品编号')),
                ('type', models.CharField(max_length=20, verbose_name='产品类型')),
                ('price', models.CharField(max_length=10, verbose_name='出售价')),
                ('describe', models.TextField(verbose_name='产品描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.CharField(default=0, max_length=1)),
            ],
        ),
    ]
